{
 "title": "Мониторинг микросервисов",
 "tags": [
  "microservices",
  "logging",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "📈 Запросы в минуту (RPM) по сервисам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({env=\"dev\"} | json | path!~\"/health\" | status_code!=\"\" [1m])) by (service)"
    }
   ]
  },
  {
   "title": "🚨 Ошибки (ERROR) по сервисам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({env=\"dev\"} |= \"ERROR\" [5m])) by (service)"
    }
   ]
  },
  {
   "title": "🔥 Тепловая карта длительности запросов (ms)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (service) (rate({env=\"dev\"} | json | unwrap duration_ms | duration_ms > 0 | __error__=\"\" [2m]))"
    }
   ]
  },
  {
   "title": "🍩 Распределение статус-кодов (за 1 час)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status_code) (count_over_time({env=\"dev\"} | json | status_code!=\"\" [1h]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "⏱ Средняя длительность (ms) по сервисам",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (service) (avg_over_time({env=\"dev\"} | json | unwrap duration_ms | duration_ms > 0 | __error__=\"\" [1h]))"
    }
   ]
  },
  {
   "title": "🔴 Количество ошибок за последние 5 минут",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({env=\"dev\"} |= \"ERROR\" [5m])"
    }
   ]
  }
 ]
}